### ISSUE TITLE
Consider non root use

### ISSUE THREAD

**Issue by ds-04** [geerlingguy/ansible-role-solr#134]
Consider non root use, e.g. ansible user with escalation on the host being configured.

Wrap <code>tasks/main.yml</code> with:

<br>
---

\- block:

  _existing_code_

  become: 'True'
...

**Comment by geerlingguy** [comment]
Thanks for the issue! For my own roles, I typically run as root since I run a service-per-server or a service-per-container, and then control permissions on that level.

Trying to work with permissions as a non-root user by default throws a lot of wrenches into the situation, so I choose to assume privileges in my own roles.

**Comment by ds-04** [comment]
Understood and am grateful this role exists.

<code>
   become: true
</code>
<br><br>
Will ensure root in situations where not root, as root is default [user] for privilege escalation.

So it should help with compatibility for others.
