### ISSUE TITLE
add feature upgrade existing solr installation

### ISSUE THREAD

**Issue by stevei101** [geerlingguy/ansible-role-solr#72]
- add feature upgrade existing solr installation

**Comment by jbilbro** [comment]
Yes we'd like this.  Not sure how to upgrade with this role as is.  Just delete /opt/solr?

**Comment by geerlingguy** [comment]
@jbilbro - Yeah, basically. Be aware that if you upgrade major versions, that can cause strange things to happen to existing indexes in `SOLR_HOME`.

I would like to support more easily switching versions, though. So far I typically support slightly older installs, so I haven't had to manage many servers that are running the bleeding edge (and thus, this hasn't been a priority for me) :(

**Comment by mberkowski** [comment]
@geerlingguy Would you be open to a PR on this? I'd envision an approach like `stat`ing `solr_install_path` to test if it's a symlink to the same or different version than `solr_version`, or I suppose just call `bin/solr version` on the installed solr, which should work for pre5 and 5+. Then run the install script with the `-f` upgrade flag if they're different instead of relying on `creates` with the solr executable to detect if it's already there.

**Comment by cdmo** [comment]
@mberkowski I'd be open to you forking the repo to add this regardless ;)

**Comment by cdmo** [comment]
just thought I'd add a little extra note. I just successfully upgraded from 7.3 to 7.4 by commenting out the task `Remove the downloaded Solr archive.` and the condition `when: solr_install_path_status.stat.isdir is not defined` on the task `Download Solr.`. I ran the play and then ssh'd into the machine I deployed to. Then ran `/root/solr-7.4.0/bin/install_solr_service.sh solr-7.4.0.tgz -n -f` from the `root` user. The `-n` was probably not necessary. That prevents solr from starting up after install. Now I didn't have any documents in my core when I did the upgrade, so that's a caveat. Thanks.

**Comment by janhoy** [comment]
I managed to upgrade by adding these as pre_tasks, controlled by the `solr_force_reinstall` variable:

    - name: Remove existing install
      file:
        path: /opt/solr
        state: absent
      when: solr_force_reinstall
    - name: Remove existing install
      file:
        path: /etc/init.d/solr
        state: absent
      when: solr_force_reinstall
    - name: Remove existing install
      file:
        path: /etc/default/solr.in.sh
        state: absent
      when: solr_force_reinstall
